---

- name: Ensure mysql-server installed
  apt: pkg=mysql-server state=installed force=yes

- name: Ensure python-mysqldb installed
  apt: pkg=python-mysqldb state=installed force=yes

- name: Ensure libmysqlclient-dev installed
  apt: pkg=libmysqlclient-dev state=installed force=yes

- name: "Create databases"
  mysql_db: name={{item.name}} state=present
  with_items: "{{ mysql_databases }}"
  run_once: true
