# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8082
  config.vm.network "forwarded_port", guest: 3306, host: 33068

  config.vm.network "private_network", ip: "192.168.56.102"

  config.vm.synced_folder "~/htdocs/linkfloyd-php", "/var/www/linkfloyd-php",
    owner: "www-data", group: "www-data"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "../provisioner/tasks.yml"
    ansible.inventory_path = "../provisioner/dev.inv"
  end
end
