---

php_packages:
    - php7.0-fpm
    - php7.0-dev
    - php7.0-cli
    - php7.0-apcu
    - php7.0-intl
    - php7.0-curl
    - php7.0-redis
    - php7.0-mysql
    - php7.0-imagick
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-xml

stack_packages:
    - nginx-extras

zend_opcache_settings:
    - { name: 'opcache.revalidate_freq', value: '0' }
    - { name: 'opcache.validate_timestamps', value: '0' }
    - { name: 'opcache.max_accelerated_files', value: '4000' }
    - { name: 'opcache.memory_consumption', value: '128' }
    - { name: 'opcache.interned_strings_buffer', value: '8' }
    - { name: 'opcache.fast_shutdown', value: '1' }
    - { name: 'opcache.enable_cli', value: '1' }

php7_cli_configuration_file: '/etc/php/7.0/cli/php.ini'
php7_fpm_configuration_file: '/etc/php/7.0/fpm/php.ini'
php7_fpm_pool_configuration_file: '/etc/php/7.0/fpm/pool.d/www.conf'
php7_fpm_settings:
    - { name: 'date.timezone', value: 'Europe/Istanbul' }
    - { name: 'expose_php', value: 'Off' }
    - { name: 'max_execution_time', value: '30' }
    - { name: 'memory_limit', value: '128M' }

php7_cli_settings:
    - { name: 'date.timezone', value: 'Europe/Istanbul' }
    - { name: 'curl.cainfo', value: '/root/cacert.pem' }

php7_fpm_pool_settings:
    - { name: 'listen', value: '127.0.0.1:9000' }
    - { name: 'listen.backlog', value: '0' }
    - { name: 'pm', value: 'static' }
    - { name: 'pm.max_children', value: '100' }
    - { name: 'pm.max_requests', value: '128' }
    - { name: 'pm.status_path', value: '/status' }
    - { name: 'ping.path', value: '/ping' }
    - { name: 'request_terminate_timeout', value: '90' }
    - { name: 'rlimit_files', value: '65535' }
    - { name: 'rlimit_core', value: 'unlimited' }
    - { name: 'catch_workers_output', value: 'yes' }
